restaurant/urls.py
from django.contrib import admin
from django.urls import path

import contents.views
import menues.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('menu/', menues.views.menu, name='menu'),
    path('privacy/', contents.views.privacy, name='privacy'),
    path('policy/', contents.views.policy, name='policy'),
]

contents/models.py
from django.db import models

# Create your models here.

        
class HTMLBlock(models.Model):
    BLOCK_CATAGORY = [{"text","Text"},{"html","HTML"},{"slide","Slide"}]
    cid = models.IntegerField
    name = models.CharField(max_length=40)
    body = models.TextField()
    create_date = models.DateTimeField()
    update_date = models.DateTimeField()
    submitter = models.CharField(max_length=30)

menues/models.py
from django.db import models

# Create your models here.

class Category(models.Model):
    id = models.IntegerField
    display_name = models.CharField(max_length=30)
    detail = models.CharField(max_length=500)
    display_image_url = models.ImageField(default=None)
    priority = models.IntegerField(default=1)

class Menu(models.Model):
    HAS_COMBO = [(0,'No'),(1,'Yes')]
    id = models.IntegerField
    display_name = models.CharField(max_length=100)
    detail = models.CharField(max_length=500)
    display_images_url = models.ImageField(default=None)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    categories = models.ManyToManyField('Category',blank=True)
    has_combo = models.BooleanField(choices=HAS_COMBO,default = 0)
    combos = models.ManyToManyField('Combo',blank=True)

class Combo(models.Model):
    id = models.IntegerField
    display_name = models.CharField(max_length=100)
    detail = models.CharField(max_length=500)
    
    display_images_url = models.ImageField(default=None)
    price = models.DecimalField(max_digits=6,decimal_places=2)
    combo_items = models.ManyToManyField('Combo_Mashup',blank=True)

class Combo_Mashup(models.Model):
    id = models.IntegerField
    display_name = models.CharField(max_length=30)
    category_items = models.IntegerField
    combo_id = models.IntegerField
    category_id = models.IntegerField

contents/views.py
from django.shortcuts import render
from django.http import HttpResponse

from .models import HTMLBlock
# Create your views here.


def privacy(request):
    contentName = "privacy"
    return blockPage(request,contentName)    


def policy(request):
    contentName = "policy"
    return blockPage(request,contentName)   
   
    

def blockPage(request,contentName):
    try:
        content = HTMLBlock.objects.get(name=contentName)
    except HTMLBlock.DoesNotExist:
        raise http404('Content not found')
    return render(request,'contents/page.html',{'content': content,})

menues/views.py
from django.shortcuts import render

# Create your views here.

from .models import Category,Menu
# Create your views here.


def menu(request):
    menues = Category.objects.all().order_by('priority')

    return render(request,'menues/menu.html',{'menuList': menues,}) 

contents/templates/contents/page.html
{% extends "layout.html" %}

{% block content %}
    {{ content.body }}
{% endblock content %}

menues/templates/menues/menu.html
{% extends "layout.html" %}

{% block content %}    
    <ul>
    {% for category in menuList %}
        <li>{{ category.display_name}}</li>
    {% endfor %}
    </ul>

    <div>
    {% for category in menuList %}
        <div id='category-{{ category.id }}'>
            {{ category.display_name}}
            {% for menuItem in category.menu_set.all %}
                <div class='menuItem'>
                    {% if menuItem.has_combo %}
                        {% for combo in menuItem.combo_set.all %}
                        <div class='menuCombo'>
                            <h4>COMBO ITEM</h4>
                            <div> {{ combo.display_name }}</div>
                            <div> {{ combo.detail }}</div>
                            <div> {{ combo.price }}</div>
                        </div>
                        {% endfor %}
                    {% endif %}
                    <div class='menuItemImage'>
                        <img src="{{ menuItem.display_images_url}}" />
                    </div>
                    <div class='menuItemName'>{{ menuItem.display_name}}</div>
                    <div class='menuItemDetail'>{{ menuItem.detail}}</div>
                    <div class='menuItemDetail'>{{ menuItem.price}}</div>

                    
                </div>
            {% endfor %}
        </div>
    {% endfor %}


    </div>
{% endblock content %}

templates/footer.html
<div class='l-pageFooter'>
    
</div>

templates/head.html
{% load static %}
<head>
    <link rel="stylesheet" href="{% static '/main.css' %}" type="text/css" media="all">
</head>

templates/header.html
<div class='l-pageHeader pageHeader'>
    <div class='l-logoContainer'>
        <div class='headerLogo'>RESTAURANT</div>
    </div>
    <div class='mobileMenuToggle'>Mobile</div>
    <div class='l-navContainer navContainer'>
        <div class ='navContent navContent--main'>
            <ul class='menuList'>
                <li class='listItem'><a href='/aboutus'>Our Story</a></li>
                <li class='listItem'><a href='/menu'>Menu</a></li>
                <li class='listItem'><a href='/Photos'>Photos</a></li>
                <li class='listItem'><a href='/Reservation'>reservation</a></li>
            </ul>
        </div>
        <div class='navContent navContent--social'>
            <ul class = 'menuList'>
                <li class='listItem'><a href='https://www.facebook.com'><i class="fab fa-facebook-f"></i></a></li>
                <li class='listItem'><a href='https://www.instagram.com'></a><i class="fab fa-instagram"></i></li>
                <li class='listItem'><a href='https://www.pintrest.com'><i class="fab fa-pinterest-p"></i></a></li>
            </ul>

        </div>
    </div>
</div>

templates/layout.html
<!DOCTYPE html>
<html lang="en" xml:lang="en">
    {% include "head.html" %}

    <body>
        <div class='l-pageContainer pageContainer'>
            {% include "header.html" %}
            <div class = 'l-pageContent'>
                {% block content %}
                {% endblock %}
            </div>

            {% include "footer.html" %}
        </div>
    </body>
</html>